// Generated by CoffeeScript 1.7.1
mapboxgl.accessToken = 'pk.eyJ1IjoiaWFtZGFuZm94IiwiYSI6ImhJUmlLZUUifQ.MjO_LzRrKOyWEuHPcBxDsg';

setTimeout(function() {
  var m;
  return m = new mapboxgl.Map({
    container: 'myMap',
    style: 'outdoors-v4.json',
    center: [40, -74.50],
    zoom: 9
  });
}, 500);
