// Generated by CoffeeScript 1.7.1
var MapBox;

MapBox = React.createClass({
  getInitialState: function() {
    return {
      mapboxgl: null
    };
  },
  statics: {
    MAPBOX_URL: 'https://api.tiles.mapbox.com/mapbox-gl-js/v0.2.0/mapbox-gl.js'
  },
  componentDidMount: function() {
    if ((this.state.mapboxgl == null) && (window.mapboxgl != null)) {
      return this.setState({
        mapboxgl: window.mapboxgl
      });
    } else {
      return this.injectMapBox();
    }
  },
  injectMapBox: function() {
    var script;
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.onload = (function(_this) {
      return function() {
        return _this.setState({
          mapboxgl: window.mapboxgl
        });
      };
    })(this);
    script.src = MapBox.MAPBOX_URL;
    return document.getElementsByTagName('head')[0].appendChild(script);
  },
  render: function() {
    return React.DOM.div(null, "MapBox goes here");
  }
});
