// Generated by CoffeeScript 1.7.1
var MapBox;

MapBox = React.createClass({
  propTypes: {
    apiToken: React.PropTypes.string.isRequired,
    id: React.PropTypes.string.isRequired
  },
  defaultProps: {
    styleUrl: 'https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v4.json'
  },
  componentDidMount: function() {
    var m;
    mapboxgl.accessToken = this.props.apiToken;
    m = new mapboxgl.Map({
      container: this.props.id,
      style: mapboxStyle,
      center: [40, -74.50],
      zoom: 9
    });
    return console.debug(m);
  },
  shouldComponentUpdate: function(nextProps, nextState) {
    console.log('shouldComponentUpdate');
    return false;
  },
  render: function() {
    return React.DOM.div({
      "style": {
        height: this.props.height,
        width: this.props.width,
        position: 'relative'
      },
      "id": this.props.id
    });
  }
});
