// Generated by CoffeeScript 1.7.1
var App, Divider, DownloadLinks, DownloadView, EleView, GPXView, HRLine, Selector, a, button, div, form, g, h1, input, p, path, rect, svg, _ref;

_ref = React.DOM, div = _ref.div, form = _ref.form, input = _ref.input, p = _ref.p, h1 = _ref.h1, a = _ref.a, button = _ref.button, svg = _ref.svg, rect = _ref.rect, path = _ref.path, g = _ref.g;

App = React.createClass({
  getInitialState: function() {
    return {
      xml: null,
      cutoff: null,
      updateCutoff: this.updateCutoff
    };
  },
  handleFile: function(e) {
    var reader;
    reader = new FileReader();
    reader.onload = (function(_this) {
      return function(evt) {
        var parser, xml;
        parser = new DOMParser();
        xml = parser.parseFromString(evt.target.result, 'text/xml');
        return _this.setState({
          xml: xml
        });
      };
    })(this);
    return reader.readAsText(e.target.files[0]);
  },
  updateCutoff: function(newCutoff) {
    return this.setState({
      cutoff: newCutoff
    });
  },
  render: function() {
    return div({}, [
      h1({}, "Strava Split"), this.state.xml == null ? p({}, "Upload a gpx file") : null, this.state.xml == null ? form({}, input({
        type: 'file',
        onChange: this.handleFile
      })) : null, this.state.xml != null ? GPXView(this.state) : null, this.state.cutoff != null ? DownloadView(this.state) : null
    ]);
  }
});

GPXView = React.createClass({
  getInitialState: function() {
    return {
      dividerX: 300
    };
  },
  render: function() {
    var data, ele, hr, i, maxEle, maxHR, maxTime, name, point, timestamp, trkpts, _i, _ref1, _ref2;
    this.start = Date.parse(this.props.xml.querySelector('trkseg trkpt:first-child time').innerHTML);
    this.end = Date.parse(this.props.xml.querySelector('trkseg trkpt:last-child time').innerHTML);
    data = {};
    trkpts = this.props.xml.getElementsByTagName('trkpt');
    _ref1 = [-Infinity, -Infinity, -Infinity], maxEle = _ref1[0], maxHR = _ref1[1], maxTime = _ref1[2];
    for (i = _i = 0, _ref2 = trkpts.length - 1; 0 <= _ref2 ? _i <= _ref2 : _i >= _ref2; i = 0 <= _ref2 ? ++_i : --_i) {
      point = trkpts[i];
      timestamp = Date.parse(point.getElementsByTagName('time')[0].innerHTML);
      data[timestamp - this.start] = {
        lat: point.getAttribute('lat'),
        lon: point.getAttribute('lon'),
        ele: ele = point.getElementsByTagName('ele')[0].innerHTML,
        hr: hr = point.getElementsByTagName('hr')[0].innerHTML
      };
      maxEle = Math.max(maxEle, ele);
      maxHR = Math.max(maxHR, hr);
      maxTime = Math.max(maxTime, timestamp);
    }
    name = this.props.xml.querySelector('name').innerHTML;
    return div({
      className: 'GPXView'
    }, [
      h1({}, name), svg({
        height: 100,
        width: 600,
        onMouseMove: this.handleMove,
        onMouseLeave: this.handleLeave,
        onClick: this.onClick,
        ref: 'svg'
      }, [
        HRLine({
          maxTime: maxTime,
          maxHR: maxHR,
          start: this.start,
          data: data
        }), EleView({
          maxTime: maxTime,
          maxEle: maxEle,
          start: this.start,
          data: data
        }), Divider({
          start: this.start,
          end: this.end,
          cutoff: this.props.cutoff,
          dividerX: this.state.dividerX
        })
      ]), p({}, this.start + " to " + this.end), Selector({
        start: this.start,
        end: this.end,
        cutoff: this.props.cutoff,
        updateCutoff: this.props.updateCutoff
      })
    ]);
  },
  handleMove: function(e) {
    rect = this.refs.svg.getDOMNode().getBoundingClientRect();
    return this.setState({
      dividerX: e.clientX - rect.left
    });
  },
  handleLeave: function(e) {
    return this.setState({
      dividerX: null
    });
  },
  onClick: function(e) {
    var c;
    console.log('click');
    c = this.state.dividerX * (this.end - this.start) / 600 + this.start;
    console.log(c);
    return this.props.updateCutoff(c);
  }
});

Divider = React.createClass({
  render: function() {
    var cutoffX;
    return g({}, [
      this.props.cutoff != null ? (cutoffX = (this.props.cutoff - this.props.start) * (600 / (this.props.end - this.props.start)), path({
        d: "M " + cutoffX + " 0 " + cutoffX + " 100",
        stroke: 'black'
      })) : null, this.props.dividerX != null ? path({
        d: "M " + this.props.dividerX + " 0 " + this.props.dividerX + " 100",
        stroke: 'black'
      }) : null
    ]);
  }
});

EleView = React.createClass({
  render: function() {
    var duration, elePath, obj, sfx, sfy, t;
    duration = this.props.maxTime - this.props.start;
    sfx = 600 / duration;
    sfy = this.props.maxEle > 100 ? 100 / this.props.maxEle : 1;
    elePath = ("M 0 " + this.props.data[0].ele + " L ") + ((function() {
      var _ref1, _results;
      _ref1 = this.props.data;
      _results = [];
      for (t in _ref1) {
        obj = _ref1[t];
        _results.push(t * sfx + " " + obj.ele * -sfy);
      }
      return _results;
    }).call(this)).join(' ') + " 600 0 Z";
    return g({
      stroke: 'none',
      fill: 'rgba(0,0,0,0.15)',
      transform: "translate(0,100)"
    }, path({
      d: elePath
    }));
  }
});

HRLine = React.createClass({
  render: function() {
    var duration, hrline, obj, sfx, sfy, t, _ref1;
    duration = this.props.maxTime - this.props.start;
    sfx = 600 / duration;
    sfy = 100 / this.props.maxHR;
    hrline = "M 0 " + this.props.data[0].hr + " L";
    _ref1 = this.props.data;
    for (t in _ref1) {
      obj = _ref1[t];
      hrline += " " + (t * sfx) + " " + (obj.hr * -sfy);
    }
    return g({
      stroke: '#dd0447',
      strokeWidth: '1.5',
      fill: 'none',
      transform: "translate(0,100)"
    }, path({
      d: hrline
    }));
  }
});

Selector = React.createClass({
  getInitialState: function() {
    return {
      value: (this.props.start + this.props.end) / 2
    };
  },
  handleChange: function() {
    var val;
    val = this.refs.slider.getDOMNode().value;
    return this.props.updateCutoff(val);
  },
  render: function() {
    return input({
      type: 'range',
      min: this.props.start,
      max: this.props.end,
      defaultValue: this.props.cutoff,
      ref: 'slider',
      onChange: this.handleChange
    });
  }
});

DownloadView = React.createClass({
  getInitialState: function() {
    return {
      computed: null
    };
  },
  handleClick: function() {
    return this.setState({
      computed: this.props.cutoff
    });
  },
  render: function() {
    return div({
      className: 'downloadView',
      ref: 'container'
    }, this.state.computed === this.props.cutoff ? DownloadLinks(this.props) : button({
      onClick: this.handleClick
    }, "Split"));
  }
});

DownloadLinks = React.createClass({
  render: function() {
    var firstTime, href1, href2, newXMLString1, newXMLString2, serializer, xml1, xml2;
    xml1 = this.props.xml;
    xml2 = xml1.cloneNode(true);
    [].forEach.call(xml1.querySelectorAll('trkseg time'), (function(_this) {
      return function(t) {
        if (Date.parse(t.innerHTML) >= _this.props.cutoff) {
          return t.parentNode.remove();
        }
      };
    })(this));
    xml1.querySelector('trk name').innerHTML += " (part 1)";
    [].forEach.call(xml2.querySelectorAll('trkseg time'), (function(_this) {
      return function(t) {
        if (Date.parse(t.innerHTML) < _this.props.cutoff) {
          return t.parentNode.remove();
        }
      };
    })(this));
    xml2.querySelector('trk name').innerHTML += " (part 2)";
    firstTime = xml2.querySelector('trk time').innerHTML;
    xml2.querySelector('metadata time').innerHTML = firstTime;
    serializer = new XMLSerializer();
    newXMLString1 = serializer.serializeToString(xml1);
    href1 = "data:application/gpx+xml;base64," + btoa(newXMLString1);
    newXMLString2 = serializer.serializeToString(xml2);
    newXMLString2 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + newXMLString2;
    href2 = "data:application/gpx+xml;base64," + btoa(newXMLString2);
    return div({}, [
      p({}, "Right click and select 'Save link as'"), a({
        href: href1
      }, "Download Part 1"), a({
        href: href2
      }, "Download Part 2")
    ]);
  }
});
